name: CI
on: [push]
jobs:
  push_to_registry:
    steps:
      runs-on: ubuntu-latest
      - uses: actions/checkout@v1.0
      - uses: docker/build-push-action@v1
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
          repository: yutachaos/kube-job-notifier
          tag_with_ref: true
          push: '${{ startsWith(github.ref, ''refs/tags/'') }}'